language: c
sudo: required
dist: xenial
addons:
  apt:
    packages:
    - musl-tools

install:
  - wget http://www.lysator.liu.se/~nisse/misc/argp-standalone-1.3.tar.gz
  - wget https://raw.githubusercontent.com/gentoo/gentoo/master/sys-libs/argp-standalone/files/argp-standalone-1.3-throw-in-funcdef.patch
  - tar -xzf argp-standalone-1.3.tar.gz

script:
  - cd argp-standalone-1.3
  - patch -p1 < ../argp-standalone-1.3-throw-in-funcdef.patch
  - export TRAVIS_COMPILER="musl-gcc"
  - export CC="musl-gcc"
  - export CC_FOR_BUILD="musl-gcc"
  - ./configure --prefix=/usr
  - sed -i '/^CFLAGS =/ s/$/ -fgnu89-inline/' Makefile
  - make
  - make install

notifications:
  email: false
