language: c
compiler: gcc
sudo: required
dist: xenial
env:
  - CC="musl-gcc"
addons:
  apt:
    packages:
    - musl-tools

install:
  - wget http://www.lysator.liu.se/~nisse/misc/argp-standalone-1.3.tar.gz
  - wget https://raw.githubusercontent.com/gentoo/gentoo/master/sys-libs/argp-standalone/files/argp-standalone-1.3-throw-in-funcdef.patch
  - tar -xzf argp-standalone-1.3.tar.gz

script:
  - cd argp-standalone-1.3
  - patch -p1 < ../argp-standalone-1.3-throw-in-funcdef.patch
  - ./configure --prefix=/usr
  - make
  - make install

notifications:
  email: false
